// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: core/event.proto

package core

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventSocialConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId    string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider  string               `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (x *EventSocialConnected) Reset() {
	*x = EventSocialConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSocialConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSocialConnected) ProtoMessage() {}

func (x *EventSocialConnected) ProtoReflect() protoreflect.Message {
	mi := &file_core_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSocialConnected.ProtoReflect.Descriptor instead.
func (*EventSocialConnected) Descriptor() ([]byte, []int) {
	return file_core_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventSocialConnected) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventSocialConnected) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventSocialConnected) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type EventSocialRankingUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId    string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider  string               `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Rank      string               `protobuf:"bytes,4,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *EventSocialRankingUpdated) Reset() {
	*x = EventSocialRankingUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSocialRankingUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSocialRankingUpdated) ProtoMessage() {}

func (x *EventSocialRankingUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_core_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSocialRankingUpdated.ProtoReflect.Descriptor instead.
func (*EventSocialRankingUpdated) Descriptor() ([]byte, []int) {
	return file_core_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventSocialRankingUpdated) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventSocialRankingUpdated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventSocialRankingUpdated) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EventSocialRankingUpdated) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

type EventLoyaltyEarned struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId    string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount    int64                `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *EventLoyaltyEarned) Reset() {
	*x = EventLoyaltyEarned{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventLoyaltyEarned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLoyaltyEarned) ProtoMessage() {}

func (x *EventLoyaltyEarned) ProtoReflect() protoreflect.Message {
	mi := &file_core_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLoyaltyEarned.ProtoReflect.Descriptor instead.
func (*EventLoyaltyEarned) Descriptor() ([]byte, []int) {
	return file_core_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventLoyaltyEarned) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventLoyaltyEarned) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventLoyaltyEarned) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_core_event_proto protoreflect.FileDescriptor

var file_core_event_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x14, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x22, 0x9e, 0x01, 0x0a, 0x19, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61,
	0x6e, 0x6b, 0x22, 0x7f, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x79, 0x61, 0x6c,
	0x74, 0x79, 0x45, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x68, 0x69, 0x6e, 0x63, 0x32, 0x37, 0x35, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x66,
	0x69, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_event_proto_rawDescOnce sync.Once
	file_core_event_proto_rawDescData = file_core_event_proto_rawDesc
)

func file_core_event_proto_rawDescGZIP() []byte {
	file_core_event_proto_rawDescOnce.Do(func() {
		file_core_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_event_proto_rawDescData)
	})
	return file_core_event_proto_rawDescData
}

var file_core_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_event_proto_goTypes = []interface{}{
	(*EventSocialConnected)(nil),      // 0: core.EventSocialConnected
	(*EventSocialRankingUpdated)(nil), // 1: core.EventSocialRankingUpdated
	(*EventLoyaltyEarned)(nil),        // 2: core.EventLoyaltyEarned
	(*timestamp.Timestamp)(nil),       // 3: google.protobuf.Timestamp
}
var file_core_event_proto_depIdxs = []int32{
	3, // 0: core.EventSocialConnected.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: core.EventSocialRankingUpdated.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: core.EventLoyaltyEarned.timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_event_proto_init() }
func file_core_event_proto_init() {
	if File_core_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventSocialConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventSocialRankingUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventLoyaltyEarned); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_event_proto_goTypes,
		DependencyIndexes: file_core_event_proto_depIdxs,
		MessageInfos:      file_core_event_proto_msgTypes,
	}.Build()
	File_core_event_proto = out.File
	file_core_event_proto_rawDesc = nil
	file_core_event_proto_goTypes = nil
	file_core_event_proto_depIdxs = nil
}
